export const portfolioBaseline = {
  tier: "TIER A - VERIFIED PS BASELINE",
  context: "April 2026 problem-statement baseline",
  projects: "1,981",
  ministries: "17",
  sectors: "22",
  originalCost: "₹37.13 lakh crore",
  revisedCost: "₹42.78 lakh crore",
  cumulativeExpenditure: "₹20.36 lakh crore",
};

export const projects = [
  {
    id: "#DEMO-RLW-01",
    name: "Eastern Dedicated Freight Corridor (Section A)",
    ministry: "Ministry of Railways",
    sector: "Transport & Logistics",
    state: "Multiple",
    status: "Ongoing",
    originalCost: "₹5,200 Cr",
    revisedCost: "₹6,800 Cr",
    expenditure: "₹4,100 Cr",
    plannedProgress: 75,
    physicalProgress: 62,
    projectRisk: "High",
    riskScore: 82,
    costRisk: "High",
    timeRisk: "High",
    implementationRisk: "Medium",
    dataConfidence: "Medium",
    primaryDriver: "Milestone Slippage",
    dataQualitySignals: [
      { type: "Completeness", status: "Pass", message: "Required fields available" },
      { type: "Consistency", status: "Warning", message: "Expenditure/progress divergence" },
      { type: "Temporal", status: "Warning", message: "Significant progress jump detected" },
      { type: "Cross-Source", status: "NA", message: "Not available in prototype" },
    ],
    validationAction:
      "Validate latest project submission before relying on the risk score for intervention prioritization.",
    tier: "TIER B - ILLUSTRATIVE DEMO DATA",
  },
  {
    id: "#DEMO-ENE-02",
    name: "Solar Park Grid Integration Hub - Phase 2",
    ministry: "Ministry of Power",
    sector: "Energy",
    state: "Rajasthan",
    status: "Ongoing",
    originalCost: "₹2,100 Cr",
    revisedCost: "₹2,100 Cr",
    expenditure: "₹1,800 Cr",
    plannedProgress: 80,
    physicalProgress: 45,
    projectRisk: "Medium",
    riskScore: 55,
    costRisk: "Low",
    timeRisk: "Medium",
    implementationRisk: "Medium",
    dataConfidence: "Low",
    primaryDriver: "Expenditure Progression",
    dataQualitySignals: [
      { type: "Completeness", status: "Pass", message: "Required fields available" },
      { type: "Consistency", status: "Fail", message: "Severe Expenditure/progress divergence" },
      { type: "Temporal", status: "Warning", message: "Repeated schedule revision" },
      { type: "Cross-Source", status: "NA", message: "Not available in prototype" },
    ],
    validationAction: "Review expenditure and progress records.",
    tier: "TIER B - ILLUSTRATIVE DEMO DATA",
  },
  {
    id: "#DEMO-WTR-03",
    name: "Urban Water Treatment Plant Expansion",
    ministry: "Ministry of Jal Shakti",
    sector: "Water & Sanitation",
    state: "Gujarat",
    status: "Delayed",
    originalCost: "₹850 Cr",
    revisedCost: "₹920 Cr",
    expenditure: "₹400 Cr",
    plannedProgress: 40,
    physicalProgress: 38,
    projectRisk: "Low",
    riskScore: 30,
    costRisk: "Low",
    timeRisk: "Low",
    implementationRisk: "Low",
    dataConfidence: "Medium",
    primaryDriver: "Milestone Delay",
    dataQualitySignals: [
      { type: "Completeness", status: "Fail", message: "Missing required monthly parameter" },
      { type: "Consistency", status: "Pass", message: "Expenditure matches progress" },
      { type: "Temporal", status: "Pass", message: "Consistent reporting" },
      { type: "Cross-Source", status: "NA", message: "Not available in prototype" },
    ],
    validationAction: "Complete data submission before risk interpretation.",
    tier: "TIER B - ILLUSTRATIVE DEMO DATA",
  },
];

export const alerts = [
  {
    id: "ALT-001",
    project: "#DEMO-RLW-01",
    type: "PROJECT RISK SIGNAL",
    signal: "Milestone slippage",
    parameter: "Schedule",
    severity: "High",
    context: "Reported progress is below planned trajectory.",
    review: "Validate milestone recovery plan.",
    confidence: "Medium",
  },
  {
    id: "ALT-002",
    project: "#DEMO-RLW-01",
    type: "DATA QUALITY SIGNAL",
    signal: "Progress jump",
    parameter: "Physical Progress",
    severity: "Medium",
    context: "Reported physical progress changed sharply compared with previous reporting period.",
    review: "Validate latest progress submission.",
    confidence: "Medium",
  },
  {
    id: "ALT-003",
    project: "#DEMO-ENE-02",
    type: "DATA QUALITY SIGNAL",
    signal: "Expenditure / progress divergence",
    parameter: "Financial vs Physical",
    severity: "High",
    context: "Financial progression differs significantly from physical progress trajectory.",
    review: "Review expenditure and progress records.",
    confidence: "Low",
  },
  {
    id: "ALT-004",
    project: "#DEMO-WTR-03",
    type: "DATA QUALITY SIGNAL",
    signal: "Missing required field",
    parameter: "Monthly Submission",
    severity: "Medium",
    context: "Required monthly parameter unavailable.",
    review: "Complete data submission.",
    confidence: "Medium",
  },
];

export const assistantResponses = {
  "Why is this project's data confidence medium?": {
    response:
      "This project has a medium data confidence score because it exhibits a significant progress jump in the recent reporting period and there is a divergence between reported expenditure and physical progress. While required fields are available, these anomalies flag the data for human verification.",
    source: "#DEMO-RLW-01 Illustrative Project Record",
  },
  "What data needs verification?": {
    response:
      "For #DEMO-RLW-01, the latest physical progress submission needs validation due to an unusual jump. For #DEMO-ENE-02, there is a severe divergence between expenditure (₹1,800 Cr) and physical progress (45%) requiring a review of expenditure records. For #DEMO-WTR-03, a required monthly parameter is missing.",
    source: "Prototype Data Quality Watchlist",
  },
  "Which projects have unusual reporting patterns?": {
    response:
      "Both #DEMO-RLW-01 and #DEMO-ENE-02 display unusual reporting patterns. #DEMO-RLW-01 has a temporal anomaly (progress jump), while #DEMO-ENE-02 has a consistency anomaly (expenditure/progress divergence).",
    source: "Data Trust & Validation Engine Signals",
  },
  "Which high-risk projects also require data verification?": {
    response:
      "#DEMO-RLW-01 is classified as High Risk (Score: 82) but only has Medium Data Confidence due to a progress jump and expenditure/progress divergence. It falls into the 'Priority verification' decision zone before intervention.",
    source: "Project Risk Profile & Data Trust Matrices",
  },
  "What are the main risk drivers for this project?": {
    response:
      "For #DEMO-RLW-01, the primary risk driver is Milestone Slippage (progress is at 62% vs planned 75%). Cost escalation is also a significant driver, with a revised cost of ₹6,800 Cr vs original ₹5,200 Cr.",
    source: "#DEMO-RLW-01 Illustrative Project Record",
  },
  "What should the monitoring team review first?": {
    response:
      "The monitoring team should first validate the latest progress submission for #DEMO-RLW-01 to confirm the reporting anomalies. Once data confidence is established, they should review the milestone recovery plan to address the schedule slippage.",
    source: "Proposed Decision Support Framework",
  },
};
